services:
  - type: web
    name: bingai
    # oregon: frankfurt
    plan: free
    env: go
    buildCommand: go build -ldflags="-s -w" -tags netgo -trimpath -o bingai main.go
    startCommand: ./bingai
